# Generated by Django 4.1.7 on 2024-03-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="intent", new_name="username",
        ),
        migrations.RenameField(
            model_name="urlsummary", old_name="summary", new_name="prompt",
        ),
        migrations.RemoveField(model_name="project", name="executive_summary",),
        migrations.RemoveField(model_name="project", name="urls_and_clean_summaries",),
        migrations.AlterField(
            model_name="urlsummary", name="url", field=models.TextField(),
        ),
    ]
